version: "3"
services:

  nodejs:
    build: ./src/nodejs
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - backend
      
  server:
    build: .
    ports: 
      - "8182:8080"
    depends_on:
      - mongodb
    links:
      - mongodb
    networks: 
      - backend
      
  mongodb: 
    image: mongo
    expose:
      - 27017
    volumes:
      - data-volume:/data/db
    restart: always
    networks: 
      - backend
volumes:
  data-volume:
  node_modules: 
  
networks:
  backend: 