version: "3"
services:
  springboot:
    build: .
    ports:
      - 8182:8080
    depends_on:
      - mongodb
    links:
      - mongodb
    networks: 
      - backend
    environment:
      DATABASE_HOST: twitterdb
      JVM_OPTS: -Xmx6g -Xms6g -XX:MaxPermSize=1024m
      
  mongodb: 
    image: mongo
    expose:
      - 27017
    volumes:
      - data-volume:/data/db
    restart: always
    networks: 
      - backend
volumes:
  data-volume:
  
networks:
  backend: 