version: "3"
services:
  springboot:
    build: .
    container_name: twitter-test
    ports:
      - 8182:8080
    working_dir: /opt/app
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    container_name: twitter-test_mongo
    environment:
      MONGO_INITDB_DATABASE: twitterdb
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
    restart: always
volumes:
  data-volume: